force-app/main/default/objects/Recipe__c/Recipe__c.object-meta.xml
<CustomObject>
    <label>Recipe</label>
    <nameField>
        <label>Recipe Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Recipe__c/fields/Coctail_type__c.field-meta.xml
<CustomField>
    <fullName>Coctail_type__c</fullName>
    <label>Coctail type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sparkling</fullName>
            </value>
            <value>
                <fullName>Classic</fullName>
            </value>
            <value>
                <fullName>Creamy</fullName>
            </value>
            <value>
                <fullName>Frozen</fullName>
            </value>
            <value>
                <fullName>Hot</fullName>
            </value>
            <value>
                <fullName>Longdrink</fullName>
            </value>
            <value>
                <fullName>Martini</fullName>
            </value>
            <value>
                <fullName>Nonalcoholic</fullName>
            </value>
            <value>
                <fullName>Shooter</fullName>
            </value>
            <value>
                <fullName>Shot</fullName>
            </value>
            <value>
                <fullName>Smoothie</fullName>
            </value>
            <value>
                <fullName>Tropical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Recipe__c/fields/Recipe_description__c.field-meta.xml
<CustomField>
    <fullName>Recipe_description__c</fullName>
    <label>Recipe description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Recipe__c/fields/Recipe_URL__c.field-meta.xml
<CustomField>
    <fullName>Recipe_URL__c</fullName>
    <label>Recipe URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Recipe_amount__c/Recipe_amount__c.object-meta.xml
<CustomObject>
    <label>Recipe amount</label>
    <nameField>
        <label>Recipe amount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recipe amounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Recipe_amount__c/fields/Ingridient_amount__c.field-meta.xml
<CustomField>
    <fullName>Ingridient_amount__c</fullName>
    <label>Ingredient amount</label>
    <precision>5</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Recipe_amount__c/fields/Recipe__c.field-meta.xml
<CustomField>
    <fullName>Recipe__c</fullName>
    <label>Recipe</label>
    <referenceTo>Recipe__c</referenceTo>
    <relationshipLabel>Recipe amounts</relationshipLabel>
    <relationshipName>Recipe_amounts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Recipe_amount__c/fields/Unit_of_measurement__c.field-meta.xml
<CustomField>
    <fullName>Unit_of_measurement__c</fullName>
    <label>Unit of measurement</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Units_of_measurements_picklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/globalValueSets/Units_of_measurements_picklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Gram</fullName>
    </customValue>
    <customValue>
        <fullName>Liter</fullName>
    </customValue>
    <customValue>
        <fullName>Milliliter</fullName>
    </customValue>
    <customValue>
        <fullName>Pieces</fullName>
    </customValue>
    <customValue>
        <fullName>Centiliter</fullName>
    </customValue>
    <customValue>
        <fullName>Teaspoon</fullName>
    </customValue>
    <masterLabel>Units of measurements picklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/RecipeController.cls
public with sharing class RecipeController {

    static Integer PAGE_SIZE = 9;

    public class Filters {
        public String searchKey { get;set; }
        public String[] categories { get;set; }
    }

    @AuraEnabled(Cacheable=true)
    public static PagedResult getRecipes(String filters, Integer pageNumber) {
        String key, whereClause = '';
        String[] categories, criteria = new String[]{};
        if (!String.isEmpty(filters)) {
            Filters coctailFilters = (Filters) JSON.deserializeStrict(filters, RecipeController.Filters.class);
            if (!String.isEmpty(coctailFilters.searchKey)) {
                key = '%' + coctailFilters.searchKey + '%';
                criteria.add('Name LIKE :key');
            }
            if (coctailFilters.categories != null) {
                categories = coctailFilters.categories;
                criteria.add('Coctail_type__c IN :categories');
            }                      
            if (criteria.size() > 0) {
                whereClause = 'WHERE ' + String.join( criteria, ' AND ' );
            }                      
        }
        Integer pageSize = RecipeController.PAGE_SIZE;
        Integer offset = (pageNumber - 1) * pageSize;
        PagedResult result =  new PagedResult();
        result.pageSize = pageSize;
        result.pageNumber = pageNumber;
        result.totalItemCount = Database.countQuery('SELECT count() FROM Recipe__c ' + whereClause);
        result.records = Database.query('SELECT Id, Name, Recipe_description__c, Coctail_type__c, Recipe_URL__c, (SELECT Id, Name , Ingridient_amount__c, Unit_of_measurement__c FROM Recipe_amounts__r) FROM Recipe__c ' + whereClause + ' ORDER BY Name LIMIT :pageSize OFFSET :offset');
        return result;
    }

    @AuraEnabled(cacheable=true)
    public static Recipe__c[] getAllRecipes() {
        return [SELECT Id, Name, Recipe_description__c, Coctail_type__c, Recipe_URL__c FROM Recipe__c];
    }

    @AuraEnabled(Cacheable=true)
    public static Recipe__c[] getSimilarProducts(Id productId, Id familyId) {
        return [SELECT Id, Name, Recipe_description__c, Coctail_type__c, Recipe_URL__c FROM Recipe__c WHERE Coctail_type__c =:familyId AND Id!=:productId];
    }

    @AuraEnabled(Cacheable=true)
    public static List<Recipe_amount__c> getRecipeAmounts(String recipeId){
        List<Recipe_amount__c> qr = null;
        String[] criteria = new String[]{};
        String whereClause = '';
        if (!String.isEmpty(recipeId)){
            criteria.add('Recipe__c = :recipeId');
            whereClause = 'WHERE ' + criteria;
            qr = Database.query('SELECT Id, Name , Ingridient_amount__c, Unit_of_measurement__c FROM Recipe_amount__c ' + whereClause);           
        }
        return qr;
    }
}